<a href="https://colab.research.google.com/github/dhanvina/Machine-Learning/blob/main/mllab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
import pandas as pd
data = datasets.load_iris()
df = pd.DataFrame(data.data,columns=data.feature_names)
df['Class'] = data.target

In [ ]:
#program 5
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)
x,y = datasets.load_iris(return_X_y=True)

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3)
ypred = model.fit(xtrain,ytrain).predict(xtest)

from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(ytest,ypred))

print(data.target_names[model.predict([[4,4,1,1]])])

In [ ]:
from sklearn.tree import export_graphviz
from six import StringIO
from IPython.display import Image
import pydotplus

dot_data = StringIO()
export_graphviz(model.estimators_[15],out_file='tree.dot',feature_names=data.feature_names,class_names=data.target_names,rounded = True,proportion=False,precision=4,filled=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('tree.png')
Image(graph.create_png())

In [ ]:
#program 6
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm

x=df.iloc[:,:2].values
y=df.iloc[:,-1].values

model = svm.SVC(kernel='linear',C=1).fit(x,y)

xmin,xmax = x[:,0].min()-1,x[:,0].max()+1
ymin,ymax = x[:,1].min()-1,x[:,1].max()+1
h=(xmax/xmin)/100

xx,yy = np.meshgrid(np.arange(xmin,xmax,h),np.arange(ymin,ymax,h))

z=model.predict(np.c_[xx.ravel(),yy.ravel()]).reshape(xx.shape)

plt.contourf(xx,yy,z,cmap=plt.cm.Paired,alpha=0.4)
plt.scatter(x[:,0],x[:,1],c=y,cmap=plt.cm.Paired)
plt.xlabel('sepal length')
plt.ylabel('sepal width')
plt.title(' svc with linear kernel')
plt.show()

In [ ]:
#program 7
import numpy as np
import pandas as pd

x=df.iloc[:,:-1].values
y=df.Class.values

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3).fit(xtrain,ytrain)

print(np.column_stack((ytest,model.predict(xtest))))

from sklearn import metrics
print("Accuracy",metrics.accuracy_score(ytrain,model.predict(xtrain)))
print("Accuracy",metrics.accuracy_score(ytest,model.predict(xtest)))
print("confusion matrix",metrics.confusion_matrix(ytrain,model.predict(xtrain)))
print("confusion matrix",metrics.confusion_matrix(ytest,model.predict(xtest)))

Accuracy 0.9583333333333334
Accuracy 0.9666666666666667
confusion matrix [[39  0  0]
 [ 0 40  2]
 [ 0  3 36]]
confusion matrix [[11  0  0]
 [ 0  7  1]
 [ 0  0 11]]
